version: '3.7'
services:
  notification-service:
    image: $DOCKER_REGISTRY_NAME/$PROJECT_NAME:dev
    ports:
      - 9090:9090
    environment:
       eureka.client.service-url.defaultZone: http://discovery-service:8761/eureka/
    restart: always
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push

networks:
  default:
    external:
      name: meetroom-microservices
